"""Apply the approved bilingual biography layout and editorial refinements."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HISTORY = ROOT / "20_Output" / "99_History"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if text.count(old) != 1:
        raise RuntimeError(f"Expected one match for {label}, found {text.count(old)}")
    return text.replace(old, new, 1)


def update(path: Path, lang: str) -> None:
    text = path.read_text(encoding="utf-8")
    archive = HISTORY / ("biografia-periodi-v1-2026-09-18.html" if lang == "it" else "biography-periods-v1-2026-09-18.html")
    if not archive.exists():
        archive.write_text(text, encoding="utf-8")

    if lang == "it":
        old_hero = '''  <div><p class="preview-kicker">Dal 1961 a oggi</p><h1>Una vita con la pittura al centro</h1><p class="lead">Da Milano alla campagna lodigiana, Gigi Montico ha fatto della pittura il suo lavoro principale e continuo, intrecciandolo con famiglia, sport, amicizie e vita nel territorio.</p><p class="preview-hero-note">Il passaggio da Milano a Dovera non interrompe la carriera. Ne cambia il contesto, portandola verso il territorio, le comunità e nuove forme di ricerca.</p><div class="preview-buttons"><a class="btn" href="#periodi">Esplora i periodi</a><a class="btn btn-secondary" href="#cronologia">Vai alla cronologia completa</a></div></div>
  <figure class="preview-hero-art"><img src="../assets/images/gigi-montico-with-sculptures.webp" width="1113" height="1300" decoding="async" alt="Gigi Montico tra le sue sculture in uno spazio espositivo"><figcaption class="preview-art-caption">Gigi Montico tra le sue sculture.</figcaption></figure>'''
        new_hero = '''  <div><p class="preview-kicker">Dal 1961 a oggi</p><h1>Una vita con la pittura al centro</h1><p class="lead">Da Milano alla campagna lodigiana, Gigi Montico ha fatto della pittura il suo lavoro principale e continuo, intrecciandolo con famiglia, sport, amicizie e vita nel territorio.</p><p class="preview-hero-note">Il passaggio da Milano a Dovera non interrompe la carriera. Ne cambia il contesto, portandola verso il territorio, le comunità e nuove forme di ricerca.</p></div>
  <div class="preview-portrait-pair">
    <figure class="preview-hero-art"><img src="../assets/images/gigi-montico-with-sculptures.webp" width="1113" height="1300" decoding="async" alt="Gigi Montico tra le sue sculture in uno spazio espositivo"><figcaption class="preview-art-caption">L'artista</figcaption></figure>
    <figure class="preview-hero-art preview-self-portrait"><img src="../assets/images/autoritratto.jpg" width="1641" height="2048" decoding="async" alt="Autoritratto di Gigi Montico"><figcaption class="preview-art-caption">Il suo autoritratto</figcaption></figure>
  </div>'''
        old_research = '<section class="preview-section" id="ricerca-artistica"><div class="preview-section-heading"><div><p class="preview-kicker">Ricerca continua</p><h2>Non una sola maniera, ma una successione di ricerche</h2></div><p>Montico cambia linguaggio quando una ricerca ha esaurito la sua spinta. Per questo opere lontane nel tempo possono sembrare di artisti diversi.</p></div><p class="phase-intro">'
        new_research = '<section class="preview-section" id="ricerca-artistica"><div class="research-intro"><p class="preview-kicker">Ricerca continua</p><h2>Non una sola maniera, ma una successione di ricerche</h2><p>Montico cambia linguaggio quando una ricerca ha esaurito la sua spinta. Per questo opere lontane nel tempo possono sembrare di artisti diversi.</p></div><p class="phase-intro">'
        old_balance = '<section class="preview-section"><div class="preview-balance"><div><p class="preview-kicker" style="color:#f0c57d">Arte e vita</p><p class="balance-quote">La pittura è stata il suo lavoro principale e continuo, dentro una vita fatta anche di famiglia, sport, amicizie e comunità.</p></div><div><h3>Una carriera dentro la vita quotidiana</h3><p>La biografia presenta insieme professione, famiglia e territorio senza trasformare la dimensione privata in una lista di date. Il filo è la continuità: dipingere, esporre, insegnare, collaborare e pubblicare in contesti diversi.</p><ul class="balance-list"><li>Milano e la riconoscibilità nel circuito artistico.</li><li>Dovera e il lavoro costruito nel territorio.</li><li>Famiglia, comunità e continuità della ricerca.</li></ul></div></div></section>'
        new_balance = '<section class="preview-section"><div class="preview-balance"><p class="preview-kicker">Arte e vita</p><p class="balance-quote">La pittura è stata il suo lavoro principale e continuo, dentro una vita fatta anche di famiglia, sport, amicizie e comunità.</p><p class="balance-copy">La continuità non coincide con l’isolamento. Montico ha costruito una carriera professionale attraversando insieme vita privata e territorio: Milano e il circuito artistico, Dovera e le comunità locali, l’insegnamento, le collaborazioni e le pubblicazioni.</p><ul class="balance-list"><li><strong>Milano</strong><span>riconoscibilità e circuito artistico</span></li><li><strong>Dovera</strong><span>studio, famiglia e territorio</span></li><li><strong>Continuità</strong><span>ricerca, relazioni e nuove immagini</span></li></ul></div></section>'
        pegaso_item = '  <li><span>18 dicembre 1970, data stimata</span> Personale alla Galleria Pegaso, Via Brera 7, Milano, a sostegno delle popolazioni colpite dal terremoto in Pakistan. L’iniziativa fu segnalata dalla rivista francese <em>La Revue moderne</em>.</li>\n'
        after = '  <li><span>1970</span> Mostre alla Galleria Motivi d\'Arte di Rapallo e alla Galleria El Fogher di Treviso; dal 17 al 31 agosto, collettiva a Diamante con Cirillo e Russo Vitale; partecipazione collettiva in Francia.</li>\n'
        pdf_box = '<section class="preview-section"><div class="preview-download"><div><p class="preview-kicker">Cronologia documentata</p><h2>Istogramma e registro completo</h2><p>Il PDF raccoglie il grafico annuale e la tabella degli eventi, con le date stimate chiaramente indicate.</p></div><a class="btn" href="../assets/documents/cronologia-eventi-gigi-montico-it.pdf" download>Scarica il PDF</a></div></section>\n'
        critical_old = '<section class="section reveal"><h2>Inquadramento critico</h2><p>La prefazione di Guido Oldani colloca Montico in prossimità del Realismo Terminale: la natura non scompare, ma assume i segni dell\'artificio contemporaneo. In questa soglia tra naturale e oggettuale si gioca l\'attualità della sua opera.</p></section>\n\n<section class="section reveal"><h2>Autoritratto</h2><figure class="hero-art"><img class="zoomable no-crop" src="../assets/images/autoritratto.jpg" alt="Autoritratto di Gigi Montico" style="width:auto;max-width:100%;max-height:52vh;display:block;margin:0 auto;"></figure></section>'
        critical_new = '<section class="section reveal"><h2>Inquadramento critico</h2><p>Nella prefazione a <em>Digital art with AI support</em>, Guido Oldani, fondatore del Realismo Terminale, osserva che Montico dà nuova vita a oggetti abbandonati o scartati per costruire immagini della natura. La novità, secondo Oldani, è proprio una natura che appare sempre più simile agli oggetti: un tratto centrale del Realismo Terminale, espresso da Montico con energia formale e cromatica.</p></section>'
        oresta_old = '<section class="section reveal"><h2>La lettura di Pierre Oresta</h2><p>Pierre Oresta interpreta'
        oresta_new = '<section class="section reveal"><h2>La lettura del professor Pierre Oresta</h2><p>Il professor Pierre Oresta, docente di italiano presso l’École Centrale de Lyon, interpreta'
    else:
        old_hero = '''  <div><p class="preview-kicker">From 1961 to today</p><h1>A life with painting at the centre</h1><p class="lead">From Milan to the Lodi countryside, Gigi Montico has made painting his principal and continuous work, alongside family, sport, friendships and life in the local community.</p><p class="preview-hero-note">The move from Milan to Dovera did not interrupt his career. It changed its context, bringing the practice closer to local communities and new forms of research.</p><div class="preview-buttons"><a class="btn" href="#periods">Explore the periods</a><a class="btn btn-secondary" href="#timeline">Go to the full timeline</a></div></div>
  <figure class="preview-hero-art"><img src="../assets/images/gigi-montico-with-sculptures.webp" width="1113" height="1300" decoding="async" alt="Gigi Montico with his sculptures in an exhibition space"><figcaption class="preview-art-caption">Gigi Montico with his sculptures.</figcaption></figure>'''
        new_hero = '''  <div><p class="preview-kicker">From 1961 to today</p><h1>A life with painting at the centre</h1><p class="lead">From Milan to the Lodi countryside, Gigi Montico has made painting his principal and continuous work, alongside family, sport, friendships and life in the local community.</p><p class="preview-hero-note">The move from Milan to Dovera did not interrupt his career. It changed its context, bringing the practice closer to local communities and new forms of research.</p></div>
  <div class="preview-portrait-pair">
    <figure class="preview-hero-art"><img src="../assets/images/gigi-montico-with-sculptures.webp" width="1113" height="1300" decoding="async" alt="Gigi Montico with his sculptures in an exhibition space"><figcaption class="preview-art-caption">The artist</figcaption></figure>
    <figure class="preview-hero-art preview-self-portrait"><img src="../assets/images/autoritratto.jpg" width="1641" height="2048" decoding="async" alt="Self-portrait by Gigi Montico"><figcaption class="preview-art-caption">His self-portrait</figcaption></figure>
  </div>'''
        old_research = '<section class="preview-section" id="artistic-research"><div class="preview-section-heading"><div><p class="preview-kicker">Continuous research</p><h2>Not one manner, but a succession of inquiries</h2></div><p>Montico changes language when a line of inquiry has reached its creative limit. Works from different periods can therefore look like they came from different artists.</p></div><p class="phase-intro">'
        new_research = '<section class="preview-section" id="artistic-research"><div class="research-intro"><p class="preview-kicker">Continuous research</p><h2>Not one manner, but a succession of inquiries</h2><p>Montico changes language when a line of inquiry has reached its creative limit. Works from different periods can therefore look like they came from different artists.</p></div><p class="phase-intro">'
        old_balance = '<section class="preview-section"><div class="preview-balance"><div><p class="preview-kicker" style="color:#f0c57d">Art and life</p><p class="balance-quote">Painting has been his principal and continuous work, within a life that also includes family, sport, friendships and community.</p></div><div><h3>A career within everyday life</h3><p>This biography presents profession, family and place together without turning private life into a list of dates. The thread is continuity: painting, exhibiting, teaching, collaborating and publishing in different contexts.</p><ul class="balance-list"><li>Milan and recognition in the art circuit.</li><li>Dovera and work rooted in the local territory.</li><li>Family, community and continuity of research.</li></ul></div></div></section>'
        new_balance = '<section class="preview-section"><div class="preview-balance"><p class="preview-kicker">Art and life</p><p class="balance-quote">Painting has been his principal and continuous work, within a life that also includes family, sport, friendships and community.</p><p class="balance-copy">Continuity does not mean isolation. Montico built a professional career alongside private life and place: Milan and its art circuit, Dovera and local communities, teaching, collaborations and publications.</p><ul class="balance-list"><li><strong>Milan</strong><span>recognition and the art circuit</span></li><li><strong>Dovera</strong><span>studio, family and local life</span></li><li><strong>Continuity</strong><span>research, relationships and new images</span></li></ul></div></section>'
        pegaso_item = '  <li><span>December 18, 1970, estimated date</span> Solo exhibition at Galleria Pegaso, 7 Via Brera, Milan, in support of those affected by the earthquake in Pakistan. The initiative was featured in the French magazine <em>La Revue moderne</em>.</li>\n'
        after = '  <li><span>1970</span> Exhibitions at Galleria Motivi d\'Arte in Rapallo and Galleria El Fogher in Treviso; a group exhibition in Diamante with Cirillo and Russo Vitale, August 17-31; participation in a group exhibition in France.</li>\n'
        pdf_box = '<section class="preview-section"><div class="preview-download"><div><p class="preview-kicker">Documented chronology</p><h2>Histogram and complete register</h2><p>The PDF brings together the annual chart and the event table, with estimated dates clearly marked.</p></div><a class="btn" href="../assets/documents/gigi-montico-events-timeline-en.pdf" download>Download the PDF</a></div></section>\n'
        critical_old = '<section class="section reveal"><h2>Critical framing</h2><p>Guido Oldani\'s preface places Montico close to Terminal Realism: nature does not disappear, but takes on the signs of contemporary artifice. The relevance of his work lies in this threshold between natural and objectual dimensions.</p></section>\n\n<section class="section reveal"><h2>Self-portrait</h2><figure class="hero-art"><img class="zoomable no-crop" src="../assets/images/autoritratto.jpg" alt="Self-portrait of Gigi Montico" style="width:auto;max-width:100%;max-height:52vh;display:block;margin:0 auto;"></figure></section>'
        critical_new = '<section class="section reveal"><h2>Critical framing</h2><p>In his preface to <em>Digital art with AI support</em>, Guido Oldani, founder of Terminal Realism, notes that Montico gives new life to abandoned or discarded objects in order to construct images of nature. For Oldani, the novelty lies in a nature that increasingly resembles objects: a central feature of Terminal Realism, expressed by Montico with formal and chromatic vitality.</p></section>'
        oresta_old = '<section class="section reveal"><h2>Pierre Oresta\'s interpretation</h2><p>Pierre Oresta interprets'
        oresta_new = '<section class="section reveal"><h2>Professor Pierre Oresta\'s interpretation</h2><p>Professor Pierre Oresta, who taught Italian at École Centrale de Lyon, interprets'

    text = replace_once(text, old_hero, new_hero, "hero")
    text = replace_once(text, old_research, new_research, "research intro")
    text = replace_once(text, old_balance, new_balance, "art and life")
    text = replace_once(text, after, after + pegaso_item, "Pegaso timeline insertion")
    pegaso_start = '<section class="section reveal"><h2>La mostra alla Galleria Pegaso</h2>' if lang == "it" else '<section class="section reveal"><h2>The exhibition at Galleria Pegaso</h2>'
    start = text.index(pegaso_start)
    end = text.index('</section>', start) + len('</section>')
    text = text[:start] + text[end:]
    text = replace_once(text, critical_old, critical_new, "critical framing and self portrait")
    text = replace_once(text, oresta_old, oresta_new, "Oresta title")
    marker = '<section class="section reveal" id="cronologia">' if lang == "it" else '<section class="section reveal" id="timeline">'
    text = replace_once(text, marker, pdf_box + marker, "PDF download block")
    if '\u2014' in text:
        raise RuntimeError(f"Em dash found in {path}")
    path.write_text(text, encoding="utf-8")


update(ROOT / "it" / "biografia.html", "it")
update(ROOT / "en" / "biography.html", "en")
print("Updated bilingual biography pages and archived the previous version.")
